language: go

go:
  - "1.11.x"

before_install:  
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get github.com/mitchellh/gox

# Below from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: "fyUIyQO8pnoOvXUmgfTkJif7Pk64cyfbY0M5u/EN4ZJbhRVOthoSY7ngVbEi4sorDGG9UYgzpmWlN9RFsnROlnZoYlcNYTuzJl5UeQhuFvrffsSCqo3FOW5uUEYsUO9Z+ypmxexN/yhLSagyVYWeO0jGlr1KwKzzbNc/8AitP89FYK/wuS8k/IAVEn/getaSWNX/K/sudwgxJQueTLMukN0uSZIJpHLyYKY+whF8/7yt+F/ONCvK8+0XHzyaMKqy6sYyp9eiaYkT9NrFD9AfSd2+ntHbSlR/mqW/d6+/6HYGtvpJ3ef/gWpvonK8DFLXTQi6XMLYYFuLn+kYPdSP9MXtu5D531uQyRZlBzbvF+gTbjnQCJEs/kSxtLQdJOo7VfYOOcAzats6KgFMfBzmJdnvMCSdThpSrl9wK24O809gWlcUg5ZirnMwy4C7rQYlzTjf6zjfXq4yg9ouUSOwpR9L1LGZDSBj1UL4Auhl/PjbCa3muqKv2yQNElXPOOk3wLWCfSnBzXH0fO2s+imXC+wNwH95YpUN72M5af0bp6vprgiecWbFkngCQCSx7s0vMi7xr86JK+l5UNkOrk+RLBI8WIfnkMYl1i0wsUvf0JbVdLiMvdcwfMi2fJH2LA/JyYrLvOcD21kkTsFcdufSPmaFNs0BlW4y+fZs/KudJAc="
  file:
    - pkg/darwin_amd64/terraform-provider-netbox
    - pkg/linux_amd64/terraform-provider-netbox
    - pkg/windows_amd64/terraform-provider-netbox.exe
  skip_cleanup: true
  on:
    tags: true
  draft: true