
[[constraint]]
  branch = "master"
  name = "github.com/digitalocean/go-netbox"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.17.2"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.17.2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.10"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"
